//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculos
    {
        public int Id { get; set; }
        public string Marca { get; set; }
        public string Modelo { get; set; }
        public string Dominio { get; set; }
        public System.DateTime AnioFabricacion { get; set; }
        public string NroMotor { get; set; }
        public System.DateTime FechaIngreso { get; set; }
        public long ValuacionIngreso { get; set; }
        public System.DateTime FechaVenta { get; set; }
        public long PrecioVenta { get; set; }
        public Nullable<int> ClienteId { get; set; }
    
        public virtual Clientes Clientes { get; set; }
    }
}
